on:
  workflow_dispatch:
    inputs:
      keyboardEnv:
        description: "Which keyboard are we building for?"
        required: true
        default: home
        type: choice
        options:
          - home
          - work

jobs:
  build_firmware_home:
    if: inputs.keyboardEnv == 'home'
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      archive_name: firmware_home
  build_firmware_work:
    if: inputs.keyboardEnv == 'work'
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      config_path: config_work
      archive_name: firmware_work
